
spring:
  application:
    name: api-gateway # اسم التطبيق في Eureka

  config:
    import: "optional:configserver:" # يخبر التطبيق بجلب التهيئة من خادم التهيئة

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # تمكين محدد موقع الاكتشاف الذي ينشئ مسارات تلقائيًا لخدمات Eureka
          lower-case-service-id: true # تحويل معرفات الخدمة إلى أحرف صغيرة
      routes:
        # مسار لخدمة المتبرعين
        - id: donor-service
          uri: lb://DONOR-SERVICE # تحميل متوازن لـ DONOR-SERVICE (اسم الخدمة في Eureka)
          predicates:
            - Path=/BloodBankApi/donors/** # توجيه الطلبات التي تبدأ بـ /BloodBankApi/donors
        # مسار لخدمة المخزون
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE # تحميل متوازن لـ INVENTORY-SERVICE
          predicates:
            - Path=/BloodBankApi/inventory/** # توجيه الطلبات التي تبدأ بـ /BloodBankApi/inventory
        - id: request-service
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path=/BloodBankApi/request/**
server:
  port: 8080 # المنفذ الافتراضي لواجهة برمجة التطبيقات (API Gateway)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # عنوان خادم الاكتشاف
    register-with-eureka: true # تسجيل واجهة برمجة التطبيقات مع Eureka
    fetch-registry: true      # جلب السجل من Eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
