
server:
  port: 8761 # Default port for Eureka Server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Eureka Server itself does not need to register with Eureka
    fetch-registry: false      # Eureka Server itself does not need to fetch registry
    service-url:
      defaultZone: http://localhost:8761/eureka/ # The URL where Eureka clients will find the server
