server:
  port: 8084
spring:
  application:
    name: request-service

  config:
    import: "optional:configserver:http://localhost:8083/"


#server:
#  port: 8084
#
#spring:
#  application:
#    name: request-service
#  config:
#    import: "configserver:http://localhost:8888"
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/