server:
  port: 8888 # المنفذ الافتراضي لخادم التهيئة

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/config-repo # هذا المسار المحلي سيعمل كمسار للملفات
          # uri: https://github.com/your-username/config-repo # يمكنك تغيير هذا إلى مستودع Git الخاص بك
          search-paths:
            - '{application}' # البحث عن ملفات التهيئة باسم التطبيق (مثل donor-service.yml, inventory-service.yml)
            - '{application}-{profile}' # البحث عن ملفات التهيئة بالملف الشخصي (مثل donor-service-dev.yml)
        # هذا للاختبار المحلي، يجب أن يكون لديك مجلد 'config-repo' في مجلد المستخدم الخاص بك
        # ويحتوي على ملفات التهيئة لكل خدمة (مثل donor-service.yml)
  application:
    name: config-server # اسم التطبيق في Eureka (سنضيف تسجيل Eureka لاحقًا إذا لزم الأمر)

eureka: # إعدادات Eureka لخادم التهيئة ليتسجل في Eureka
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # عنوان خادم الاكتشاف
    register-with-eureka: true # تسجيل خادم التهيئة مع Eureka
    fetch-registry: true      # جلب السجل من Eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
